#!/bin/bash

#SBATCH --job-name=preprocess_steps
#SBATCH --ntasks=32
#SBATCH --ntasks-per-socket=8
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3G
#SBATCH --time=06:00:00
#SBATCH --qos=6hours
#SBATCH --error=myerror%A_%a.err

ml purge
ml picard/2.9.2
ml bwa-mem2/2.2.1-foss-2018b

bwa-mem2 mem -t8 -M /data/reference/gch38.fa /data/fastqfiles/sample_1.1.fq /data/fastqfiles/sample_1.2.fq > /alignment/sample_1.sam
	  
java -jar $EBROOTPICARD/picard.jar AddOrReplaceReadGroups \
  INPUT=/alignment/sample1_.sam  OUTPUT=/alignment/sample_1.bam SORT_ORDER=coordinate \
  RGID=A00684.1 RGLB=P2021 RGPL=ILLUMINA RGPU=A00684:110:H2TYCXY:1 RGSM=Sample1_1

java -jar $EBROOTPICARD/picard.jar MarkDuplicates INPUT=/alignment/sample_1.bam OUTPUT=/alignment/duplicate/sample_1_dedup.bam METRICS_FILE=/alignment/duplicate/sample_1_dedupmetrics.txt  
java -jar $EBROOTPICARD/picard.jar BuildBamIndex INPUT=/alignment/duplicate/sample_1_dedup.bam
