#!/bin/bash

#SBATCH --job-name=recal_sample1
#SBATCH --ntasks=4
#SBATCH --ntasks-per-socket=4
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=2G
#SBATCH --time=3-00:00:00
#SBATCH --qos=1week
#SBATCH --output=myoutput%A_%a.out
#SBATCH --error=myerror%A_%a.err

ml purge
ml GATK/4.2.2.0-foss-2018b-Java-1.8
ml R/4.1.0-foss-2018b

gatk BaseRecalibrator \
-I /alignment/duplicate/sample_1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_1_recal_data.table

gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_1_recal_data.table -plots /alignment/bqsr/sample_1_covariates.pdf

gatk ApplyBQSR \
  -R /data/reference/gch38.fa \
  -I /alignment/duplicate/sample_1_dedup.bam \
  --bqsr-recal-file /alignment/bqsr/sample1_recal_data.table \
  -O /alignment/bqsr/sample1_1_recal.bam
  
gatk BaseRecalibrator \
  -I /alignment/bqsr/sample_1_recal.bam \
  -R data/reference/gch38.fa \
  --known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
  -O /alignment/bqsr/sample_1_recal_datacorr.table
