#!/bin/bash

#SBATCH --job-name=array_covariates
#SBATCH --ntasks=32
#SBATCH --ntasks-per-socket=8
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --time=06:00:00
#SBATCH --qos=6hours
#SBATCH --output=myoutput%A_%a.out
#SBATCH --error=myerror%A_%a.err
#SBATCH --array=1-6
ml purge
ml GATK/4.2.2.0-foss-2018b-Java-1.8
ml R/4.1.0-foss-2018b

(head -$SLURM_ARRAY_TASK_ID commands_covariates | tail -1)
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_1_recal_data.table -plots /alignment/bqsr/sample_1_covariates.pdf
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_2_recal_data.table -plots /alignment/bqsr/sample_2_covariates.pdf
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_3_recal_data.table -plots /alignment/bqsr/sample_3_covariates.pdf
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_4_recal_data.table -plots /alignment/bqsr/sample_4_covariates.pdf
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_5_recal_data.table -plots /alignment/bqsr/sample_5_covariates.pdf
gatk AnalyzeCovariates -bqsr /alignment/bqsr/sample_6_recal_data.table -plots /alignment/bqsr/sample_6_covariates.pdf
