#!/bin/bash

#SBATCH --job-name=GenotypeGVCFs
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G
#SBATCH --time=3-00:00:00
#SBATCH --qos=1week
#SBATCH --output=myoutput%A_%a.out
#SBATCH --error=myerror%A_%a.err
ml GATK/4.2.2.0-foss-2018b-Java-1.8

 gatk --java-options "-Xmx4g" GenotypeGVCFs \
   -R /data/reference/gch38.fa \
   -V /variants/cohort.g.vcf.gz \
   -O /variants/cohort.vcf.gz
