#!/bin/bash

#SBATCH --job-name=array_recal
#SBATCH --ntasks=12
#SBATCH --ntasks-per-socket=5
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=2G
#SBATCH --time=24:00:00
#SBATCH --qos=1day
#SBATCH --output=myoutput%A_%a.out
#SBATCH --error=myerror%A_%a.err
#SBATCH --array=1-6
ml purge
ml GATK/4.2.2.0-foss-2018b-Java-1.8
(head -$SLURM_ARRAY_TASK_ID commands_bcal | tail -1)

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_1_recal_data.table

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_2_recal_data.table

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_3_recal_data.table

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_4_recal_data.table

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_5_recal_data.table

gatk BaseRecalibrator \
-I /alignment/duplicate/1_dedup.bam \
-R /data/reference/gch38.fa \
-known-sites /data/index_dict/GCF_000001405.39_newcontiglines.vcf.gz \
-O /alignment/bqsr/sample_6_recal_data.table

