#!/bin/bash

#SBATCH --job-name=validatebam
#SBATCH --ntasks=32
#SBATCH --ntasks-per-socket=8
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --time=04:00:00
#SBATCH --qos=6hours
#SBATCH --output=myoutput%A_%a.out
#SBATCH --error=myerror%A_%a.err
#SBATCH --array=1-6

ml purge
ml picard/2.9.2

(head -$SLURM_ARRAY_TASK_ID commands_val | tail -1)
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_1_recal.bam \
      MODE=VERBOSE
      
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_2_recal.bam \
      MODE=VERBOSE
      
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_3_recal.bam \
      MODE=VERBOSE
      
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_4_recal.bam \
      MODE=VERBOSE
      
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_5_recal.bam \
      MODE=VERBOSE
      
java -jar $EBROOTPICARD/picard.jar ValidateSamFile \
      I=/alignment/bqsr/sample_6_recal.bam \
      MODE=VERBOSE                              
